### ISSUE TITLE
Test suite failing to fetch catalogue

### ISSUE THREAD

**Issue by duncanmmacleod** [mattpitkin/psrqpy#116]
I am seeing reproducible failures of the psqrpy 1.2.4 test suite when it attempts to download the catalogue. This can be reproduced simply by

```python
$ python -c "import psrqpy; print(psrqpy.QueryATNF())"
Traceback (most recent call last):
  File "/home/duncan.macleod/.conda/envs/psrqpy/lib/python3.11/site-packages/psrqpy/utils.py", line 161, in get_catalogue
    float(val)
ValueError: could not convert string to float: '*'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/duncan.macleod/.conda/envs/psrqpy/lib/python3.11/site-packages/psrqpy/search.py", line 351, in get_catalogue
    dbtable = get_catalogue(path_to_db=path_to_db, cache=cache,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duncan.macleod/.conda/envs/psrqpy/lib/python3.11/site-packages/psrqpy/utils.py", line 163, in get_catalogue
    raise ValueError("Value with error is not convertable to a float")
ValueError: Value with error is not convertable to a float

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/duncan.macleod/.conda/envs/psrqpy/lib/python3.11/site-packages/psrqpy/search.py", line 216, in __init__
    _ = self.get_catalogue(path_to_db=loadfromdb, cache=cache,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duncan.macleod/.conda/envs/psrqpy/lib/python3.11/site-packages/psrqpy/search.py", line 355, in get_catalogue
    raise RuntimeError("Problem getting catalogue: {}".format(str(e)))
RuntimeError: Problem getting catalogue: Value with error is not convertable to a float
```

<details>
<summary>Environment info</summary>

```console
$ conda list
# packages in environment at /home/duncan.macleod/.conda/envs/psrqpy:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
ads                       0.12.3                     py_2    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
astropy                   5.2.1           py311hcb2cf0a_0    conda-forge
attrs                     22.2.0             pyh71513ae_0    conda-forge
beautifulsoup4            4.11.1             pyha770c72_0    conda-forge
brotli                    1.0.9                h166bdaf_8    conda-forge
brotli-bin                1.0.9                h166bdaf_8    conda-forge
brotlipy                  0.7.0           py311hd4cff14_1005    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2022.12.7            ha878542_0    conda-forge
certifi                   2022.12.7          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py311h409f033_3    conda-forge
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
contourpy                 1.0.6           py311h4dd048b_0    conda-forge
cryptography              39.0.0          py311h9b4c7bb_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
exceptiongroup            1.1.0              pyhd8ed1ab_0    conda-forge
fonttools                 4.38.0          py311hd4cff14_1    conda-forge
freetype                  2.12.1               hca18f0e_1    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
importlib-metadata        6.0.0              pyha770c72_0    conda-forge
iniconfig                 2.0.0              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h166bdaf_2    conda-forge
kiwisolver                1.4.4           py311h4dd048b_1    conda-forge
lcms2                     2.14                 hfd0df8a_1    conda-forge
ld_impl_linux-64          2.39                 hcc3a1bd_1    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libblas                   3.9.0           16_linux64_openblas    conda-forge
libbrotlicommon           1.0.9                h166bdaf_8    conda-forge
libbrotlidec              1.0.9                h166bdaf_8    conda-forge
libbrotlienc              1.0.9                h166bdaf_8    conda-forge
libcblas                  3.9.0           16_linux64_openblas    conda-forge
libdeflate                1.14                 h166bdaf_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgfortran-ng            12.2.0              h69a702a_19    conda-forge
libgfortran5              12.2.0              h337968e_19    conda-forge
libgomp                   12.2.0              h65d4601_19    conda-forge
libjpeg-turbo             2.1.4                h166bdaf_0    conda-forge
liblapack                 3.9.0           16_linux64_openblas    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.21          pthreads_h78a6416_3    conda-forge
libpng                    1.6.39               h753d276_0    conda-forge
libsqlite                 3.40.0               h753d276_0    conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libtiff                   4.5.0                h82bc61c_0    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libwebp-base              1.2.4                h166bdaf_0    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
markupsafe                2.1.1           py311hd4cff14_2    conda-forge
matplotlib-base           3.6.2           py311he728205_0    conda-forge
mock                      5.0.1              pyhd8ed1ab_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
numpy                     1.24.1          py311hbde0eaa_0    conda-forge
openjpeg                  2.5.0                hfec8fc6_2    conda-forge
openssl                   3.0.7                h0b41bf4_1    conda-forge
packaging                 23.0               pyhd8ed1ab_0    conda-forge
pandas                    1.5.2           py311h2872171_2    conda-forge
pillow                    9.4.0           py311h104bd61_0    conda-forge
pluggy                    1.0.0              pyhd8ed1ab_5    conda-forge
pooch                     1.6.0              pyhd8ed1ab_0    conda-forge
psrqpy                    1.2.4              pyhd8ed1ab_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyerfa                    2.0.0.1         py311h4c7f6c3_3    conda-forge
pyopenssl                 23.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
pytest                    7.2.0              pyhd8ed1ab_2    conda-forge
pytest-socket             0.5.1              pyhd8ed1ab_0    conda-forge
python                    3.11.0          ha86cf86_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.11                    3_cp311    conda-forge
pytz                      2022.7             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0             py311hd4cff14_5    conda-forge
readline                  8.1.2                h0f457ee_0    conda-forge
requests                  2.28.1             pyhd8ed1ab_1    conda-forge
scipy                     1.10.0          py311h8e6699e_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
soupsieve                 2.3.2.post1        pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tzdata                    2022g                h191b570_0    conda-forge
urllib3                   1.26.14            pyhd8ed1ab_0    conda-forge
werkzeug                  2.2.2              pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
zipp                      3.11.0             pyhd8ed1ab_0    conda-forge
zstd                      1.5.2                h6239696_4    conda-forge
```

</details>

<details>
<summary>PyTest traceback</summary>

```python
$ python -m pytest --pyargs psrqpy.tests -ra -v -x
======================================== test session starts =========================================
platform linux -- Python 3.11.0, pytest-7.2.0, pluggy-1.0.0 -- /home/duncan.macleod/.conda/envs/psrqpy/bin/python
cachedir: .pytest_cache
rootdir: /home/duncan.macleod
plugins: socket-0.5.1
collected 36 items

.conda/envs/psrqpy/lib/python3.11/site-packages/psrqpy/tests/query_test.py::test_crab ERROR    [  2%]

=============================================== ERRORS ===============================================
____________________________________ ERROR at setup of test_crab _____________________________________

path_to_db = None, cache = True, update = False, pandas = True, version = '1.69'

    def get_catalogue(
        path_to_db=None, cache=True, update=False, pandas=False, version="latest"
    ):
        """
        This function will attempt to download and cache the entire ATNF Pulsar
        Catalogue database `tarball
        <http://www.atnf.csiro.au/people/pulsar/psrcat/downloads/psrcat_pkg.tar.gz>`_,
        or read in database file from a provided path. The database will be
        converted into an :class:`astropy.table.Table` or
        :class:`pandas.DataFrame`. This was originally based on the method in the
        `ATNF.ipynb
        <https://github.com/astrophysically/ATNF-Pulsar-Cat/blob/master/ATNF.ipynb>`_
        notebook by Joshua Tan (`@astrophysically
        <https://github.com/astrophysically/>`_).

        Args:
            path_to_db (str): if the path to a local version of the database file
                is given then that will be read in rather than attempting to
                download the file (defaults to None).
            cache (bool): cache the downloaded ATNF Pulsar Catalogue file. Defaults
                to True. This is ignored if `path_to_db` is given. The cache file
                path uses the specification in the `appdirs
                <https://github.com/ActiveState/appdirs>`_ package to set the
                location.
            update (bool): if True the ATNF Pulsar Catalogue will be
                re-downloaded and cached if there has been a change compared to the
                currently cached version. This is ignored if `path_to_db` is given.
            pandas (bool): if True the catalogue will be returned as a
                :class:`pandas.DataFrame` rather than the default of an
                :class:`~astropy.table.Table`.
            version (str): the version string (without the leading "v") of the ATNF
                catalogue version to download. This defaults to "latest" to get the
                most up-to-date version.

        Returns:
            :class:`~astropy.table.Table` or :class:`~pandas.DataFrame`: a table
            containing the entire catalogue.

        """

        if path_to_db is None:
            # remove any cached file if requested
            if update:
                if check_update():
                    os.remove(os.path.join(CACHEDIR, DEFAULTCACHENAME))

            if version == "latest":
                atnftarball = ATNF_TARBALL
            else:
                atnftarball = ATNF_VERSION_TARBALL.format(version)

            # get the tarball
            try:
                dbtarfile = download_atnf_tarball(
                    atnftarball, usecache=cache, version=version
                )
            except RuntimeError as e:
                raise IOError(
                    f"Problem accessing ATNF catalogue tarball: {atnftarball}\n{e}"
                )

            try:
                # open tarball
                pulsargz = tarfile.open(dbtarfile, mode="r:gz")

                # extract the database file
                dbfile = pulsargz.extractfile("psrcat_tar/psrcat.db")
            except IOError:
                raise IOError("Problem extracting the database file")
        else:
            try:
                dbfile = open(path_to_db, "r")
            except IOError:
                raise IOError("Error loading given database file")

        breakstring = "@"  # break between each pulsar
        commentstring = "#"  # specifies line is a comment

        # create list of dictionaries - one for each pulsar
        psrlist = [{}]

        version = None  # catalogue version

        # loop through lines in dbfile
        for line in dbfile.readlines():
            if isinstance(line, str):
                dataline = line.split()
            else:
                dataline = line.decode().split()  # Splits on whitespace

            if dataline[0][0] == commentstring:
                # get catalogue version (should be in first comment string)
                if dataline[0] == "#CATALOGUE" and len(dataline) == 2:
                    version = dataline[1]
                continue

            if dataline[0][0] == breakstring:
                # First break comes at the end of the first object and so forth
                psrlist.append({})  # New object!
                continue

            try:
                psrlist[-1][dataline[0]] = float(dataline[1])
            except ValueError:
                psrlist[-1][dataline[0]] = dataline[1]

            if len(dataline) > 2:
                # check whether 3rd value is a float (so its an error value) or not
                try:
                    float(dataline[2])
                    isfloat = True
                except ValueError:
                    isfloat = False

                if isfloat:
                    # error values are last digit errors, so convert to actual
                    # errors by finding the number of decimal places after the
                    # '.' in the value string
                    val = dataline[1].split(":")[-1]  # account for RA and DEC strings

                    try:
>                       float(val)
E                       ValueError: could not convert string to float: '*'

.conda/envs/psrqpy/lib/python3.11/site-packages/psrqpy/utils.py:161: ValueError

During handling of the above exception, another exception occurred:

self = <[KeyError("Sorting by attribute 'JNAME' is not possible as it is not in the table") raised in repr()] QueryATNF object at 0x7f23de7042d0>
path_to_db = None, cache = True, update = False, overwrite = True, version = 'latest'

    def get_catalogue(self, path_to_db=None, cache=True, update=False,
                      overwrite=True, version="latest"):
        """
        Call the :func:`psrqpy.utils.get_catalogue` function to download the
        ATNF Pulsar Catalogue, or load a given catalogue path.

        Args:
            path_to_db (str): if the path to a local version of the database
                file is given then that will be read in rather than attempting to
                download the file (defaults to None).
            cache (bool): cache the downloaded ATNF Pulsar Catalogue file. Defaults
                to True. This is ignored if `path_to_db` is given.
            update (bool): if True the ATNF Pulsar Catalogue will be
                re-downloaded and cached if there has been a change compared to the
                currently cached version. This is ignored if `path_to_db` is given.
            overwrite (bool): if True the returned catalogue will overwrite the
                catalogue currently contained within the :class:`~psrqpy.QueryATNF`
                class. If False then a new :class:`~psrqpy.QueryATNF` copy of the
                catalogue will be returned.
            version (str): the version string (without the leading "v") of the ATNF
                catalogue version to download. This defaults to "latest" to get the
                most up-to-date version.

        Returns:
            :class:`psrqpy.QueryATNF`: a table containing the catalogue.
        """
        from .utils import get_catalogue

        cachefile = os.path.join(CACHEDIR, f"query_{version}.pkl")

        if cache and not update and path_to_db is None:
            # check if cache file exists
            try:
                self.load(cachefile, cleardfonly=True)
                return self
            except IOError:
                pass

        try:
>           dbtable = get_catalogue(path_to_db=path_to_db, cache=cache,
                                    update=update, pandas=True,
                                    version=version)

.conda/envs/psrqpy/lib/python3.11/site-packages/psrqpy/search.py:351:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

path_to_db = None, cache = True, update = False, pandas = True, version = '1.69'

    def get_catalogue(
        path_to_db=None, cache=True, update=False, pandas=False, version="latest"
    ):
        """
        This function will attempt to download and cache the entire ATNF Pulsar
        Catalogue database `tarball
        <http://www.atnf.csiro.au/people/pulsar/psrcat/downloads/psrcat_pkg.tar.gz>`_,
        or read in database file from a provided path. The database will be
        converted into an :class:`astropy.table.Table` or
        :class:`pandas.DataFrame`. This was originally based on the method in the
        `ATNF.ipynb
        <https://github.com/astrophysically/ATNF-Pulsar-Cat/blob/master/ATNF.ipynb>`_
        notebook by Joshua Tan (`@astrophysically
        <https://github.com/astrophysically/>`_).

        Args:
            path_to_db (str): if the path to a local version of the database file
                is given then that will be read in rather than attempting to
                download the file (defaults to None).
            cache (bool): cache the downloaded ATNF Pulsar Catalogue file. Defaults
                to True. This is ignored if `path_to_db` is given. The cache file
                path uses the specification in the `appdirs
                <https://github.com/ActiveState/appdirs>`_ package to set the
                location.
            update (bool): if True the ATNF Pulsar Catalogue will be
                re-downloaded and cached if there has been a change compared to the
                currently cached version. This is ignored if `path_to_db` is given.
            pandas (bool): if True the catalogue will be returned as a
                :class:`pandas.DataFrame` rather than the default of an
                :class:`~astropy.table.Table`.
            version (str): the version string (without the leading "v") of the ATNF
                catalogue version to download. This defaults to "latest" to get the
                most up-to-date version.

        Returns:
            :class:`~astropy.table.Table` or :class:`~pandas.DataFrame`: a table
            containing the entire catalogue.

        """

        if path_to_db is None:
            # remove any cached file if requested
            if update:
                if check_update():
                    os.remove(os.path.join(CACHEDIR, DEFAULTCACHENAME))

            if version == "latest":
                atnftarball = ATNF_TARBALL
            else:
                atnftarball = ATNF_VERSION_TARBALL.format(version)

            # get the tarball
            try:
                dbtarfile = download_atnf_tarball(
                    atnftarball, usecache=cache, version=version
                )
            except RuntimeError as e:
                raise IOError(
                    f"Problem accessing ATNF catalogue tarball: {atnftarball}\n{e}"
                )

            try:
                # open tarball
                pulsargz = tarfile.open(dbtarfile, mode="r:gz")

                # extract the database file
                dbfile = pulsargz.extractfile("psrcat_tar/psrcat.db")
            except IOError:
                raise IOError("Problem extracting the database file")
        else:
            try:
                dbfile = open(path_to_db, "r")
            except IOError:
                raise IOError("Error loading given database file")

        breakstring = "@"  # break between each pulsar
        commentstring = "#"  # specifies line is a comment

        # create list of dictionaries - one for each pulsar
        psrlist = [{}]

        version = None  # catalogue version

        # loop through lines in dbfile
        for line in dbfile.readlines():
            if isinstance(line, str):
                dataline = line.split()
            else:
                dataline = line.decode().split()  # Splits on whitespace

            if dataline[0][0] == commentstring:
                # get catalogue version (should be in first comment string)
                if dataline[0] == "#CATALOGUE" and len(dataline) == 2:
                    version = dataline[1]
                continue

            if dataline[0][0] == breakstring:
                # First break comes at the end of the first object and so forth
                psrlist.append({})  # New object!
                continue

            try:
                psrlist[-1][dataline[0]] = float(dataline[1])
            except ValueError:
                psrlist[-1][dataline[0]] = dataline[1]

            if len(dataline) > 2:
                # check whether 3rd value is a float (so its an error value) or not
                try:
                    float(dataline[2])
                    isfloat = True
                except ValueError:
                    isfloat = False

                if isfloat:
                    # error values are last digit errors, so convert to actual
                    # errors by finding the number of decimal places after the
                    # '.' in the value string
                    val = dataline[1].split(":")[-1]  # account for RA and DEC strings

                    try:
                        float(val)
                    except ValueError:
>                       raise ValueError("Value with error is not convertable to a float")
E                       ValueError: Value with error is not convertable to a float

.conda/envs/psrqpy/lib/python3.11/site-packages/psrqpy/utils.py:163: ValueError

During handling of the above exception, another exception occurred:

    @pytest.fixture(scope="module")
    def query():
>       return QueryATNF()

.conda/envs/psrqpy/lib/python3.11/site-packages/psrqpy/tests/conftest.py:11:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
.conda/envs/psrqpy/lib/python3.11/site-packages/psrqpy/search.py:216: in __init__
    _ = self.get_catalogue(path_to_db=loadfromdb, cache=cache,
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <[KeyError("Sorting by attribute 'JNAME' is not possible as it is not in the table") raised in repr()] QueryATNF object at 0x7f23de7042d0>
path_to_db = None, cache = True, update = False, overwrite = True, version = 'latest'

    def get_catalogue(self, path_to_db=None, cache=True, update=False,
                      overwrite=True, version="latest"):
        """
        Call the :func:`psrqpy.utils.get_catalogue` function to download the
        ATNF Pulsar Catalogue, or load a given catalogue path.

        Args:
            path_to_db (str): if the path to a local version of the database
                file is given then that will be read in rather than attempting to
                download the file (defaults to None).
            cache (bool): cache the downloaded ATNF Pulsar Catalogue file. Defaults
                to True. This is ignored if `path_to_db` is given.
            update (bool): if True the ATNF Pulsar Catalogue will be
                re-downloaded and cached if there has been a change compared to the
                currently cached version. This is ignored if `path_to_db` is given.
            overwrite (bool): if True the returned catalogue will overwrite the
                catalogue currently contained within the :class:`~psrqpy.QueryATNF`
                class. If False then a new :class:`~psrqpy.QueryATNF` copy of the
                catalogue will be returned.
            version (str): the version string (without the leading "v") of the ATNF
                catalogue version to download. This defaults to "latest" to get the
                most up-to-date version.

        Returns:
            :class:`psrqpy.QueryATNF`: a table containing the catalogue.
        """
        from .utils import get_catalogue

        cachefile = os.path.join(CACHEDIR, f"query_{version}.pkl")

        if cache and not update and path_to_db is None:
            # check if cache file exists
            try:
                self.load(cachefile, cleardfonly=True)
                return self
            except IOError:
                pass

        try:
            dbtable = get_catalogue(path_to_db=path_to_db, cache=cache,
                                    update=update, pandas=True,
                                    version=version)
        except Exception as e:
>           raise RuntimeError("Problem getting catalogue: {}".format(str(e)))
E           RuntimeError: Problem getting catalogue: Value with error is not convertable to a float

.conda/envs/psrqpy/lib/python3.11/site-packages/psrqpy/search.py:355: RuntimeError
====================================== short test summary info =======================================
ERROR .conda/envs/psrqpy/lib/python3.11/site-packages/psrqpy/tests/query_test.py::test_crab - RuntimeError: Problem getting catalogue: Value with error is not convertable to a float
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
========================================== 1 error in 4.76s ==========================================
```

</details>

**Comment by mattpitkin** [comment]
There must be some issue with the latest version (1.69) of the ATNF Pulsar Catalogue. This sometimes happens when it gets updated and contains a typo or some formatting issue. If you explicitly specify the previous version:

```python
python -c "import psrqpy; print(psrqpy.QueryATNF(version=1.68))"
``` 

it will work.

Unfortunately, the catalogue errors are often first caught when the psrqpy CI fails. I'll look into this later and send a fix to the catalogue maintainers if/when I find the issue.

**Comment by duncanmmacleod** [comment]
I think the issue is that some entries in the catalogue are being preesented with a `PX` (whatever that is) that includes asterisks (`*`) in place of actual values for RA and DEC, e.g. J1518+0204C from [here](https://www.atnf.csiro.au/research/pulsar/psrcat/proc_form.php?version=1.69&Name=Name&PX=PX&startUserDefined=true&c1_val=&c2_val=&c3_val=&c4_val=&sort_attr=jname&sort_order=asc&condition=&pulsar_names=&ephemeris=short&coords_unit=raj%2Fdecj&radius=&coords_1=&coords_2=&style=Long+with+last+digit+error&no_value=*&fsize=3&x_axis=&x_scale=linear&y_axis=&y_scale=linear&state=query&table_bottom.x=71&table_bottom.y=24).

Are asterisks supposed to be acceptable values?

**Comment by mattpitkin** [comment]
Yep, I've just found that too.

In the database file that psrqpy reads (the `psrcat.db` file within [`psrcat_pkg.tar.gz`](https://www.atnf.csiro.au/people/pulsar/psrcat/downloads/psrcat_pkg.tar.gz), asterisks should not be present. If the value of, e.g., `PX` (parallax) is not known for a pulsar then there should just be no entry for `PX` given.

It only seems to be that one pulsar, J1518+0204C, that is effected by this, so I'll ask for that to be fixed.

**Comment by duncanmmacleod** [comment]
Is it reasonable to patch `psrqpy` to handle `*` as `null`, or is that just going to cause myriad problems downstream?

**Comment by mattpitkin** [comment]
> Is it reasonable to patch psrqpy to handle * as null, or is that just going to cause myriad problems downstream?

That could be done, but it might make it harder to catch more problematic errors within the catalogue.

> Is it also reasonable to configure a nightly (or weekly) run of the psrqpy CI workflow to catch these errors 'automatically' (given that ATNF don't seem to be doing their own QA)?

This is a good idea. I assume it's easy enough to set up a github action to run periodically. I think this could be done nightly as the test suite doesn't take too long and it should fall over quickly if there's a problem.
