### ISSUE TITLE
Error retrieving ATNF tarball

### ISSUE THREAD

**Issue by cherryng** [mattpitkin/psrqpy#81]
I am getting a 503 service unavailable error when I try to download and query the database. Pasting the error below. I googled around and didn't find any fixes. Wondering if you have any idea what is going on? I am using the following package versions:
```
python                    3.9.1                h88f2d9e_2
astropy                   4.2.1            py39he3068b8_1
psrqpy                    1.1.1              pyhd8ed1ab_0    conda-forge
```

The error:
```
>>> query = QueryATNF()
Traceback (most recent call last):
  File "/Users/cherryng/miniconda3/lib/python3.9/site-packages/psrqpy/utils.py", line 76, in get_catalogue
    dbtarfile = download_file(ATNF_TARBALL, cache=cache)
  File "/Users/cherryng/miniconda3/lib/python3.9/site-packages/astropy/utils/data.py", line 1257, in download_file
    raise errors[sources[0]]
  File "/Users/cherryng/miniconda3/lib/python3.9/site-packages/astropy/utils/data.py", line 1222, in download_file
    f_name = _download_file_from_source(
  File "/Users/cherryng/miniconda3/lib/python3.9/site-packages/astropy/utils/data.py", line 1051, in _download_file_from_source
    with urlopener.open(req, timeout=timeout) as remote:
  File "/Users/cherryng/miniconda3/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/Users/cherryng/miniconda3/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/Users/cherryng/miniconda3/lib/python3.9/urllib/request.py", line 555, in error
    result = self._call_chain(*args)
  File "/Users/cherryng/miniconda3/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/Users/cherryng/miniconda3/lib/python3.9/urllib/request.py", line 747, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/Users/cherryng/miniconda3/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/Users/cherryng/miniconda3/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/Users/cherryng/miniconda3/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/Users/cherryng/miniconda3/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/Users/cherryng/miniconda3/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cherryng/miniconda3/lib/python3.9/site-packages/psrqpy/search.py", line 336, in get_catalogue
    dbtable = get_catalogue(path_to_db=path_to_db, cache=cache,
  File "/Users/cherryng/miniconda3/lib/python3.9/site-packages/psrqpy/utils.py", line 78, in get_catalogue
    raise IOError("Problem accessing ATNF catalogue tarball")
OSError: Problem accessing ATNF catalogue tarball

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/cherryng/miniconda3/lib/python3.9/site-packages/psrqpy/search.py", line 214, in __init__
    _ = self.get_catalogue(path_to_db=loadfromdb, cache=cache,
  File "/Users/cherryng/miniconda3/lib/python3.9/site-packages/psrqpy/search.py", line 339, in get_catalogue
    raise RuntimeError("Problem getting catalogue: {}".format(str(e)))
RuntimeError: Problem getting catalogue: Problem accessing ATNF catalogue tarball

```

**Comment by mattpitkin** [comment]
@cherryng if I go to https://www.atnf.csiro.au/research/pulsar/psrcat/ at the moment it looks like the catalogue webpage is down, so hopefully this will be fixed soon and everything will work again.

**Comment by mattpitkin** [comment]
It looks like the catalogue webpage is up and running again, so hopefully psrqpy will work. I'll close this issue for now, but @cherryng do let me know if the problem persists.
